# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created: Fri May 27 00:05:50 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(443, 419)
        icon = QtGui.QIcon()
        icon.addFile(_fromUtf8(":/images/images/new.png"))
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.vboxlayout = QtGui.QVBoxLayout(self.centralwidget)
        self.vboxlayout.setMargin(9)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.outputLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(5), QtGui.QSizePolicy.Policy(5))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.outputLabel.sizePolicy().hasHeightForWidth())
        self.outputLabel.setSizePolicy(sizePolicy)
        self.outputLabel.setFrameShape(QtGui.QFrame.StyledPanel)
        self.outputLabel.setText(_fromUtf8(""))
        self.outputLabel.setObjectName(_fromUtf8("outputLabel"))
        self.vboxlayout.addWidget(self.outputLabel)
        self.equationEditor = QtGui.QTextEdit(self.centralwidget)
        self.equationEditor.setObjectName(_fromUtf8("equationEditor"))
        self.vboxlayout.addWidget(self.equationEditor)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 443, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Edit = QtGui.QMenu(self.menubar)
        self.menu_Edit.setObjectName(_fromUtf8("menu_Edit"))
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setOrientation(QtCore.Qt.Horizontal)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(4, self.toolBar)
        self.newAction = QtGui.QAction(MainWindow)
        self.newAction.setIcon(icon)
        self.newAction.setObjectName(_fromUtf8("newAction"))
        self.updateAction = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addFile(_fromUtf8(":/images/images/update.png"))
        self.updateAction.setIcon(icon1)
        self.updateAction.setObjectName(_fromUtf8("updateAction"))
        self.saveAsAction = QtGui.QAction(MainWindow)
        self.saveAsAction.setEnabled(False)
        self.saveAsAction.setObjectName(_fromUtf8("saveAsAction"))
        self.saveAction = QtGui.QAction(MainWindow)
        self.saveAction.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addFile(_fromUtf8(":/images/images/save.png"))
        self.saveAction.setIcon(icon2)
        self.saveAction.setObjectName(_fromUtf8("saveAction"))
        self.exitAction = QtGui.QAction(MainWindow)
        self.exitAction.setObjectName(_fromUtf8("exitAction"))
        self.increaseTextAction = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addFile(_fromUtf8(":/images/images/larger.png"))
        self.increaseTextAction.setIcon(icon3)
        self.increaseTextAction.setObjectName(_fromUtf8("increaseTextAction"))
        self.decreaseTextAction = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addFile(_fromUtf8(":/images/images/smaller.png"))
        self.decreaseTextAction.setIcon(icon4)
        self.decreaseTextAction.setObjectName(_fromUtf8("decreaseTextAction"))
        self.increaseMathAction = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addFile(_fromUtf8(":/images/images/mathlarger.png"))
        self.increaseMathAction.setIcon(icon5)
        self.increaseMathAction.setObjectName(_fromUtf8("increaseMathAction"))
        self.decreaseMathAction = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addFile(_fromUtf8(":/images/images/mathsmaller.png"))
        self.decreaseMathAction.setIcon(icon6)
        self.decreaseMathAction.setObjectName(_fromUtf8("decreaseMathAction"))
        self.aboutAction = QtGui.QAction(MainWindow)
        self.aboutAction.setObjectName(_fromUtf8("aboutAction"))
        self.aboutQtAction = QtGui.QAction(MainWindow)
        self.aboutQtAction.setObjectName(_fromUtf8("aboutQtAction"))
        self.menu_File.addAction(self.newAction)
        self.menu_File.addAction(self.saveAction)
        self.menu_File.addAction(self.saveAsAction)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.exitAction)
        self.menu_Edit.addAction(self.updateAction)
        self.menu_Help.addAction(self.aboutAction)
        self.menu_Help.addAction(self.aboutQtAction)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.toolBar.addAction(self.newAction)
        self.toolBar.addAction(self.saveAction)
        self.toolBar.addAction(self.updateAction)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.increaseTextAction)
        self.toolBar.addAction(self.decreaseTextAction)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.increaseMathAction)
        self.toolBar.addAction(self.decreaseMathAction)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.increaseTextAction, QtCore.SIGNAL(_fromUtf8("triggered()")), self.equationEditor.zoomIn)
        QtCore.QObject.connect(self.decreaseTextAction, QtCore.SIGNAL(_fromUtf8("triggered()")), self.equationEditor.zoomOut)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MathTran Equation Viewer [*]", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Edit.setTitle(QtGui.QApplication.translate("MainWindow", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.newAction.setText(QtGui.QApplication.translate("MainWindow", "&New", None, QtGui.QApplication.UnicodeUTF8))
        self.updateAction.setText(QtGui.QApplication.translate("MainWindow", "&Update", None, QtGui.QApplication.UnicodeUTF8))
        self.updateAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Return", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAsAction.setText(QtGui.QApplication.translate("MainWindow", "Save &As...", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAction.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.exitAction.setText(QtGui.QApplication.translate("MainWindow", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.exitAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.increaseTextAction.setText(QtGui.QApplication.translate("MainWindow", "&Increase Text Size", None, QtGui.QApplication.UnicodeUTF8))
        self.increaseTextAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+=", None, QtGui.QApplication.UnicodeUTF8))
        self.decreaseTextAction.setText(QtGui.QApplication.translate("MainWindow", "&Decrease Text Size", None, QtGui.QApplication.UnicodeUTF8))
        self.decreaseTextAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+-", None, QtGui.QApplication.UnicodeUTF8))
        self.increaseMathAction.setText(QtGui.QApplication.translate("MainWindow", "Increase Math Size", None, QtGui.QApplication.UnicodeUTF8))
        self.decreaseMathAction.setText(QtGui.QApplication.translate("MainWindow", "Decrease Math Size", None, QtGui.QApplication.UnicodeUTF8))
        self.aboutAction.setText(QtGui.QApplication.translate("MainWindow", "&About...", None, QtGui.QApplication.UnicodeUTF8))
        self.aboutQtAction.setText(QtGui.QApplication.translate("MainWindow", "About &Qt...", None, QtGui.QApplication.UnicodeUTF8))

import mathtran_rc
